sudo: enabled
language: python
dist: trusty
addons:
  chrome: stable
python:
    - "3.5"
    - "3.6"
    - "3.6-dev"  # 3.6 development branch
env:
    global:
     - TRAVIS=true
# command to install dependencies
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - python manage.py runserver 0.0.0.0:8000 # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8000 http://0.0.0.0 &
install:
  - pip install -r requirements.txt

script:
  - python manage.py test
  - sh run_tests.sh
