sudo: enabled
language: python
dist: trusty
addons:
  chrome: stable
python:
    - "3.5"
    - "3.6"
    - "3.6-dev"  # 3.6 development branch
env:
    global:
     - TRAVIS=true
# command to install dependencies
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8000 http://0.0.0.0 &
install:
  - pip install -r requirements.txt

script:
  - python manage.py test
  - sh run_tests.sh
